# Generated by Django 3.2 on 2022-06-02 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='title')),
                ('slug', models.CharField(max_length=255, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.CharField(max_length=255, verbose_name='slug')),
                ('content', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('time_crete', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Top 10 Cartoons',
                'verbose_name_plural': 'Top 10 Cartoons',
                'ordering': ['-time_crete', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Film_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Top10Cartoons.category')),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Top10Cartoons.film')),
            ],
            options={
                'unique_together': {('category_id', 'film_id')},
            },
        ),
        migrations.AddField(
            model_name='film',
            name='category',
            field=models.ManyToManyField(through='Top10Cartoons.Film_Category', to='Top10Cartoons.Category'),
        ),
    ]
